
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PUNTO = 8;
  public static final int PORC = 14;
  public static final int CONJUNTO = 2;
  public static final int LLAVEI = 5;
  public static final int BARRA = 11;
  public static final int FLECHA = 4;
  public static final int LLAVED = 6;
  public static final int POR = 13;
  public static final int COMA = 20;
  public static final int EOF = 0;
  public static final int COMILLA = 19;
  public static final int ALFAMIN = 18;
  public static final int DEC = 21;
  public static final int ALFAMAY = 17;
  public static final int error = 1;
  public static final int INTERR = 9;
  public static final int DIP = 3;
  public static final int RAN = 16;
  public static final int ENTERO = 15;
  public static final int DPUNTOS = 7;
  public static final int MAS = 12;
  public static final int PTCOMA = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONJUNTO",
  "DIP",
  "FLECHA",
  "LLAVEI",
  "LLAVED",
  "DPUNTOS",
  "PUNTO",
  "INTERR",
  "PTCOMA",
  "BARRA",
  "MAS",
  "POR",
  "PORC",
  "ENTERO",
  "RAN",
  "ALFAMAY",
  "ALFAMIN",
  "COMILLA",
  "COMA",
  "DEC"
  };
}

